from typing import List, Literal, Optional
from pydantic import BaseModel, Field


class EvaluateRequest(BaseModel):
    rule_text: str = Field(..., description="The proposed underwriting decline rule text")
    insurer_name: Optional[str] = Field(None, description="Name of the insurer proposing the rule")
    supporting_rationale: Optional[str] = Field(
        None, description="The insurer's stated justification for the rule"
    )
    actuarial_data_provided: bool = Field(
        False, description="Whether the insurer has provided actuarial data to support the rule"
    )


class LevelResult(BaseModel):
    level: int
    name: str
    status: Literal["PASS", "FLAG", "FAIL"]
    findings: str
    relevant_references: List[str]
    rejection_reasons_identified: List[str]


class EvaluateResponse(BaseModel):
    rule_text: str
    insurer_name: Optional[str]
    overall_recommendation: Literal["APPROVE", "FLAG_FOR_REVIEW", "DECLINE"]
    overall_score: float = Field(..., description="Compliance score 0-100; higher is better")
    summary: str
    levels: List[LevelResult]
    human_review_required: bool = True
    disclaimer: str = (
        "This assessment is generated by an AI system and is intended to support — not replace — "
        "human regulatory review. Final decisions must be made by qualified FSRA regulatory analysts. "
        "Level 1 non-compliance is typically a full-stop basis for refusal."
    )


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class ChatRequest(BaseModel):
    message: str
    history: List[ChatMessage] = Field(default_factory=list)


class ChatResponse(BaseModel):
    response: str
    history: List[ChatMessage]
